apiVersion: v1
kind: Service
metadata:
  name: quiz-db
  namespace: quiz-app-namespace
spec:
  selector:
    app: quiz-db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP

