apiVersion: apps/v1
kind: Deployment
metadata:
  name: quiz-service
  labels:
    app: quiz-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quiz-service
  template:
    metadata:
      name: quiz-service
      labels:
        app: quiz-service
    spec:
      containers:
        - name: quiz-service
          image: pavanvarikolu/quiz-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8090
          envFrom:
            - configMapRef:
                name: quiz-service-config
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: quiz-service
spec:
  selector:
    app: quiz-service
  ports:
    - protocol: TCP
      port: 8090
      targetPort: 8090
  type: LoadBalancer
      