apiVersion: v1
kind: Service
metadata:
  name: quiz-service
  namespace: quiz-app-namespace
spec:
  selector:
    app: quiz-deployment
  ports:
    - protocol: TCP
      port: 8090
      targetPort: 8090
      nodePort: 30090
  type: NodePort

