apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-registry
  namespace: quiz-app-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-registry
  template:
    metadata:
      labels:
        app: service-registry
    spec:
      containers:
        - name: service-registry-container
          image: pavanvarikolu/service-registry:latest
          ports:
            - containerPort: 8761
          env:
            - name: EUREKA_CLIENT_FETCH_REGISTRY
              value: "false"
            - name: EUREKA_CLIENT_REGISTER_WITH_EUREKA
              value: "false"
            - name: EUREKA_INSTANCE_HOSTNAME
              value: service-registry
            - name: SERVER_PORT
              value: "8761"
      restartPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  name: service-registry
  namespace: quiz-app-namespace
spec:
  selector:
    app: service-registry
  ports:
    - protocol: TCP
      port: 8761
      targetPort: 8761
  type: LoadBalancer
