apiVersion: v1
kind: Service
metadata:
  name: question-service
  namespace: quiz-app-namespace
spec:
  selector:
    app: question-deployment
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30080
  type: NodePort

