version: '3.8'
services:
  service-registry:
    container_name: service-registry-container
    image: pavanvarikolu/service-registry:1.1
    ports:
      - 8761:8761

  db:
    image: postgres:latest
    container_name: postgresdb
    environment:
      - POSTGRES_USER=${SPRING_DATASOURCE_USERNAME}
      - POSTGRES_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - POSTGRES_DB=${SPRING_DATABASE}
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  question-service:
    build: .
    container_name: question-service-container
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/${SPRING_DATABASE}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
    depends_on:
      - service-registry
      - db
    ports:
      - "8080:8080"

volumes:
  db-data:
