name: Microservices CI/CD Pipeline

on:
  push:
    branches:
      - main
      - api-gateway
      - question-service
      - quiz-service
      - service-registry
  pull_request:
    branches:
      - main

jobs:
  service-registry-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build service-registry
        run: |
          cd service-registry
          chmod +x mvnw 
          ./mvnw clean install

  question-service-build:
    runs-on: ubuntu-latest
    needs: service-registry-build  # Ensure service-registry completes first
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build question-service
        run: |
          cd question-service
          chmod +x mvnw
          ./mvnw clean install

  quiz-service-build:
    runs-on: ubuntu-latest
    needs: question-service-build  # Ensure question-service completes first
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build quiz-service
        run: |
          cd quiz-service
          chmod +x mvnw
          ./mvnw clean install

  api-gateway-build:
    runs-on: ubuntu-latest
    needs: quiz-service-build  # Ensure quiz-service completes first
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build api-gateway
        run: |
          cd api-gateway
          chmod +x mvnw
          ./mvnw clean install
